"""users table

Revision ID: 418d805499e6
Revises: 7caa0b47c6b3
Create Date: 2019-04-16 00:14:59.820761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418d805499e6'
down_revision = '7caa0b47c6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plan', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'travel_plan', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travel_plan', type_='foreignkey')
    op.drop_column('travel_plan', 'user_id')
    # ### end Alembic commands ###
