"""users table

Revision ID: 68b4e32d4a47
Revises: 
Create Date: 2019-03-26 00:02:29.246436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b4e32d4a47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenditures', sa.Column('travel_plan_id', sa.Integer(), nullable=True))
    op.drop_constraint('expenditures_travel_plan_fkey', 'expenditures', type_='foreignkey')
    op.create_foreign_key(None, 'expenditures', 'travel_plan', ['travel_plan_id'], ['id'])
    op.drop_column('expenditures', 'travel_plan')
    op.add_column('travel_plan', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('travel_plan_country_fkey', 'travel_plan', type_='foreignkey')
    op.create_foreign_key(None, 'travel_plan', 'country', ['country_id'], ['id'])
    op.drop_column('travel_plan', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plan', sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'travel_plan', type_='foreignkey')
    op.create_foreign_key('travel_plan_country_fkey', 'travel_plan', 'country', ['country'], ['id'])
    op.drop_column('travel_plan', 'country_id')
    op.add_column('expenditures', sa.Column('travel_plan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenditures', type_='foreignkey')
    op.create_foreign_key('expenditures_travel_plan_fkey', 'expenditures', 'travel_plan', ['travel_plan'], ['id'])
    op.drop_column('expenditures', 'travel_plan_id')
    # ### end Alembic commands ###
