"""users table

Revision ID: 7caa0b47c6b3
Revises: bbff2b54189d
Create Date: 2019-04-15 00:29:59.009075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caa0b47c6b3'
down_revision = 'bbff2b54189d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plan', sa.Column('date_start', sa.Date(), nullable=False))
    op.create_index(op.f('ix_travel_plan_date_start'), 'travel_plan', ['date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_plan_date_start'), table_name='travel_plan')
    op.drop_column('travel_plan', 'date_start')
    # ### end Alembic commands ###
