"""all table

Revision ID: bbff2b54189d
Revises: 
Create Date: 2019-04-11 00:04:01.963121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbff2b54189d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('travel_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_plan_date_end'), 'travel_plan', ['date_end'], unique=False)
    op.create_index(op.f('ix_travel_plan_date_start'), 'travel_plan', ['date_start'], unique=False)
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_plan_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sum_plan', sa.Numeric(), nullable=True),
    sa.Column('sum_real', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['travel_plan_id'], ['travel_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expand_expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expenditure_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sum_plan', sa.Numeric(), nullable=True),
    sa.Column('sum_real', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['expenditure_id'], ['expenditures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expand_expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_travel_plan_date_start'), table_name='travel_plan')
    op.drop_index(op.f('ix_travel_plan_date_end'), table_name='travel_plan')
    op.drop_table('travel_plan')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('country')
    # ### end Alembic commands ###
