"""expand table

Revision ID: e7514901d107
Revises: 68b4e32d4a47
Create Date: 2019-04-01 13:18:41.619838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7514901d107'
down_revision = '68b4e32d4a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expand_expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expenditure_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sum_plan', sa.Numeric(), nullable=True),
    sa.Column('sum_real', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['expenditure_id'], ['expenditures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expand_expenditures')
    # ### end Alembic commands ###
